#!/usr/bin/env bash
#A bash script to ping an IP address passed as an argument 5 times on terminal

if [[ $1 == "" ]]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping "$1" -c 5;
fi
