#!/usr/bin/env bash
# A Bash script to display to infinity and beyond indefinitely

#Requirement: In between each iteration of the loop, add a sleep 2

while true; do
	echo "To infinity and beyond"
	sleep 2
done
