#!/usr/bin/env bash
# A script to loop from 1 to 10 and:
#	display bad luck for the 4th loop iteration
#	display good luck for the 8th loop iteration
#	display Holberton School for the other iterations

k=1
while [ $k -le 10 ]; do
	if [ $k -eq 4 ]; then
		echo "bad luck"
	elif [ $k -eq 8 ]; then
		echo "good luck"
	else
		echo "Holberton School";
	fi
	let "k++";
done
