#!/usr/bin/env bash
# A script to display numbers from 1 to 20 and:
#	display 4 and then bad luck from China for the 4th loop iteration
#	display 9 and then bad luck from Japan for the 9th loop iteration
#	display 17 and then bad luck from Italy for the 17th loop iteration

k=1
while [ $k -le 20 ]; do
	echo "$k"
	case "$k" in
	4)
		echo "bad luck from China" ;;
	9)
		echo "bad luck from Japan" ;;
	17)
		echo "bad luck from Italy" ;;
	esac
	let "k++"
done
