#!/usr/bin/env bash
# A Bash script to display the time for 12 hours and 59 minutes:
#	display hours from 0 to 12
#	display minutes from 1 to 59

k=1
m=0
while [ $m -le 12 ]; do
	echo "Hour: $j";
	while [ $k -le 59 ]; do
		echo "$k"
		let "k++"
	done
	k=1
	let "m++"
done
