#!/usr/bin/env bash
# A Bash script to display:
#	The content of the current directory
#	In a list format
#	Where only the part of the name after the first dash is displayed (refer to the example)
#	You must use the for loop (while and until are forbidden)
#	Do not display hidden files

LIST=$(ls)
for k in $LIST; do
	echo "$k" | cut -d "-" --complement -f 1
done
